.PHONY build:
build:
	@echo Building...
	go mod tidy
	go build -o task
.PHONY lint:
lint:
	@echo Linting...
	golangci-lint run
.PHONY bench:
bench:
	@echo Running benchmark ...
	go test -bench=. ./...
.PHONY test:
test:
	@echo Running benchmark ...
	go test ./...
build-docker:
	@echo Building docker ...
	docker build -t $(name) .
